server:
  port: ${SERVER_PORT:8080}

sparql:
  endpoint: ${SPARQL_ENDPOINT:http://localhost:8890/sparql}
  defaultGraphUri: ${TARGET_GRAPH:http://mu.semte.ch/application}
  metaDirectory: ${META_DIRECTORY:/Users/bittichn/IdeaProjects/poc-uri-info-service-v2/test/data/tdb}

resource-labels:
  enabled: ${RESOURCE_LABELS_ENABLED:true}
  endpoint: ${RESOURCE_LABELS_ENDPOINT:http://localhost/resource-labels}
spring:
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:512MB}
      max-file-size: ${MAX_FILE_SIZE:512MB}
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
